import { defineBuildConfig } from "unbuild";

export default defineBuildConfig({
  clean: true,
  declaration: true,
  entries: [
    "./src/accountability",
    "./src/collection",
    "./src/event",
    "./src/field",
    "./src/file",
    "./src/filter",
    "./src/flow",
    "./src/generic",
    "./src/geometry",
    "./src/item",
    "./src/notification",
    "./src/overview",
    "./src/permission",
    "./src/policy",
    "./src/preset",
    "./src/query",
    "./src/relation",
    "./src/schema",
    "./src/setting",
    "./src/share",
    "./src/storage",
    "./src/user",
    "./src/version",
    "./src/index",
  ],
  externals: ["geojson", "knex"],
  rollup: { emitCJS: true },
});
